# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8bc93f4c97676287848938f2bd2f58445cbeeb28a0b2d67c2f6ea07e3258a6aa68e06f7f25b5c13ecb38b3066303f36506d025ac2ecab7d16c87fb60ec4f8b29

test:
  secret_key_base: 1191a5600e95128ece1e9aeb6affa97c3d9a21a9249d412bbadf772bc3dd0d0b36e867815b30d291abbc1971d6d196cb85421214ada94ac077eada0699875c85

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
